// PatternsDefault.jsx

const correspondence = [
    { "name": "The Fool", "file": "a-00.svg" },
    { "name": "The Magician", "file": "a-01.svg" },
    { "name": "The High Priestess", "file": "a-02.svg" },
    { "name": "The Empress", "file": "a-03.svg" },
    { "name": "The Emperor", "file": "a-04.svg" },
    { "name": "The Hierophant", "file": "a-05.svg" },
    { "name": "The Lovers", "file": "a-06.svg" },
    { "name": "The Chariot", "file": "a-07.svg" },
    { "name": "Strength", "file": "a-08.svg" },
    { "name": "The Hermit", "file": "a-09.svg" },
    { "name": "Wheel of Fortune", "file": "a-10.svg" },
    { "name": "Justice", "file": "a-11.svg" },
    { "name": "The Hanged Man", "file": "a-12.svg" },
    { "name": "Death", "file": "a-13.svg" },
    { "name": "Temperance", "file": "a-14.svg" },
    { "name": "The Devil", "file": "a-15.svg" },
    { "name": "The Tower", "file": "a-16.svg" },
    { "name": "The Star", "file": "a-17.svg" },
    { "name": "The Moon", "file": "a-18.svg" },
    { "name": "The Sun", "file": "a-19.svg" },
    { "name": "Judgement", "file": "a-20.svg" },
    { "name": "The World", "file": "a-21.svg" },
    { "name": "Ace of Wands", "file": "w-01.svg" },
    { "name": "Two of Wands", "file": "w-02.svg" },
    { "name": "Three of Wands", "file": "w-03.svg" },
    { "name": "Four of Wands", "file": "w-04.svg" },
    { "name": "Five of Wands", "file": "w-05.svg" },
    { "name": "Six of Wands", "file": "w-06.svg" },
    { "name": "Seven of Wands", "file": "w-07.svg" },
    { "name": "Eight of Wands", "file": "w-08.svg" },
    { "name": "Nine of Wands", "file": "w-09.svg" },
    { "name": "Ten of Wands", "file": "w-10.svg" },
    { "name": "Page of Wands", "file": "w-11.svg" },
    { "name": "Knight of Wands", "file": "w-12.svg" },
    { "name": "Queen of Wands", "file": "w-13.svg" },
    { "name": "King of Wands", "file": "w-14.svg" },
    { "name": "Ace of Pentacles", "file": "p-01.svg" },
    { "name": "Two of Pentacles", "file": "p-02.svg" },
    { "name": "Three of Pentacles", "file": "p-03.svg" },
    { "name": "Four of Pentacles", "file": "p-04.svg" },
    { "name": "Five of Pentacles", "file": "p-05.svg" },
    { "name": "Six of Pentacles", "file": "p-06.svg" },
    { "name": "Seven of Pentacles", "file": "p-07.svg" },
    { "name": "Eight of Pentacles", "file": "p-08.svg" },
    { "name": "Nine of Pentacles", "file": "p-09.svg" },
    { "name": "Ten of Pentacles", "file": "p-10.svg" },
    { "name": "Page of Pentacles", "file": "p-11.svg" },
    { "name": "Knight of Pentacles", "file": "p-12.svg" },
    { "name": "Queen of Pentacles", "file": "p-13.svg" },
    { "name": "King of Pentacles", "file": "p-14.svg" },
    { "name": "Ace of Swords", "file": "s-01.svg" },
    { "name": "Two of Swords", "file": "s-02.svg" },
    { "name": "Three of Swords", "file": "s-03.svg" },
    { "name": "Four of Swords", "file": "s-04.svg" },
    { "name": "Five of Swords", "file": "s-05.svg" },
    { "name": "Six of Swords", "file": "s-06.svg" },
    { "name": "Seven of Swords", "file": "s-07.svg" },
    { "name": "Eight of Swords", "file": "s-08.svg" },
    { "name": "Nine of Swords", "file": "s-09.svg" },
    { "name": "Ten of Swords", "file": "s-10.svg" },
    { "name": "Page of Swords", "file": "s-11.svg" },
    { "name": "Knight of Swords", "file": "s-12.svg" },
    { "name": "Queen of Swords", "file": "s-13.svg" },
    { "name": "King of Swords", "file": "s-14.svg" },
    { "name": "Ace of Cups", "file": "c-01.svg" },
    { "name": "Two of Cups", "file": "c-02.svg" },
    { "name": "Three of Cups", "file": "c-03.svg" },
    { "name": "Four of Cups", "file": "c-04.svg" },
    { "name": "Five of Cups", "file": "c-05.svg" },
    { "name": "Six of Cups", "file": "c-06.svg" },
    { "name": "Seven of Cups", "file": "c-07.svg" },
    { "name": "Eight of Cups", "file": "c-08.svg" },
    { "name": "Nine of Cups", "file": "c-09.svg" },
    { "name": "Ten of Cups", "file": "c-10.svg" },
    { "name": "Page of Cups", "file": "c-11.svg" },
    { "name": "Knight of Cups", "file": "c-12.svg" },
    { "name": "Queen of Cups", "file": "c-13.svg" },
    { "name": "King of Cups", "file": "c-14.svg" }
];

export { correspondence };
