// StaticValue.jsx

const cardsAdditional = [
    { "name": "The Fool", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "0" },
    { "name": "The Magician", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "I" },
    { "name": "The High Priestess", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "II" },
    { "name": "The Empress", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "III" },
    { "name": "The Emperor", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "IV" },
    { "name": "The Hierophant", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "V" },
    { "name": "The Lovers", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "VI" },
    { "name": "The Chariot", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "VII" },
    { "name": "Strength", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "VIII" },
    { "name": "The Hermit", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "IX" },
    { "name": "Wheel of Fortune", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "X" },
    { "name": "Justice", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "XI" },
    { "name": "The Hanged Man", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "XII" },
    { "name": "Death", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "XIII" },
    { "name": "Temperance", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "XIV" },
    { "name": "The Devil", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "XV" },
    { "name": "The Tower", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "XVI" },
    { "name": "The Star", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "XVII" },
    { "name": "The Moon", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "XVIII" },
    { "name": "The Sun", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "XIX" },
    { "name": "Judgement", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "XX" },
    { "name": "The World", "majorArcana": true, "minorArcana": false, "suit": null, "role": null, "number": "XXI" },
    { "name": "Ace of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": null, "number": null },
    { "name": "Two of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": null, "number": null },
    { "name": "Three of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": null, "number": null },
    { "name": "Four of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": null, "number": null },
    { "name": "Five of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": null, "number": null },
    { "name": "Six of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": null, "number": null },
    { "name": "Seven of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": null, "number": null },
    { "name": "Eight of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": null, "number": null },
    { "name": "Nine of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": null, "number": null },
    { "name": "Ten of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": null, "number": null },
    { "name": "Page of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": "Page", "number": null },
    { "name": "Knight of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": "Knight", "number": null },
    { "name": "Queen of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": "Queen", "number": null },
    { "name": "King of Wands", "majorArcana": false, "minorArcana": true, "suit": "Wands", "role": "King", "number": null },
    { "name": "Ace of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": null, "number": null },
    { "name": "Two of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": null, "number": null },
    { "name": "Three of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": null, "number": null },
    { "name": "Four of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": null, "number": null },
    { "name": "Five of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": null, "number": null },
    { "name": "Six of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": null, "number": null },
    { "name": "Seven of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": null, "number": null },
    { "name": "Eight of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": null, "number": null },
    { "name": "Nine of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": null, "number": null },
    { "name": "Ten of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": null, "number": null },
    { "name": "Page of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": "Page", "number": null },
    { "name": "Knight of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": "Knight", "number": null },
    { "name": "Queen of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": "Queen", "number": null },
    { "name": "King of Pentacles", "majorArcana": false, "minorArcana": true, "suit": "Pentacles", "role": "King", "number": null },
    { "name": "Ace of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": null, "number": null },
    { "name": "Two of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": null, "number": null },
    { "name": "Three of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": null, "number": null },
    { "name": "Four of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": null, "number": null },
    { "name": "Five of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": null, "number": null },
    { "name": "Six of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": null, "number": null },
    { "name": "Seven of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": null, "number": null },
    { "name": "Eight of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": null, "number": null },
    { "name": "Nine of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": null, "number": null },
    { "name": "Ten of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": null, "number": null },
    { "name": "Page of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": "Page", "number": null },
    { "name": "Knight of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": "Knight", "number": null },
    { "name": "Queen of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": "Queen", "number": null },
    { "name": "King of Swords", "majorArcana": false, "minorArcana": true, "suit": "Swords", "role": "King", "number": null },
    { "name": "Ace of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": null, "number": null },
    { "name": "Two of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": null, "number": null },
    { "name": "Three of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": null, "number": null },
    { "name": "Four of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": null, "number": null },
    { "name": "Five of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": null, "number": null },
    { "name": "Six of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": null, "number": null },
    { "name": "Seven of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": null, "number": null },
    { "name": "Eight of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": null, "number": null },
    { "name": "Nine of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": null, "number": null },
    { "name": "Ten of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": null, "number": null },
    { "name": "Page of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": "Page", "number": null },
    { "name": "Knight of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": "Knight", "number": null },
    { "name": "Queen of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": "Queen", "number": null },
    { "name": "King of Cups", "majorArcana": false, "minorArcana": true, "suit": "Cups", "role": "King", "number": null }
];

export { cardsAdditional };